version: '3'

services:
  app:
    build:
      context: ./front
      dockerfile: Dockerfile

    volumes: 
      - type: bind
        source: ./front
        target: /app

    working_dir: /app

    tty: true

    ports:
      - "3000:3000"

    command: bash