version: "3"

services:
  app:
    build:
      context: ./front
      dockerfile: Dockerfile

    volumes:
      - type: bind
        source: ./front
        target: /app

    working_dir: /app

    tty: true

    ports:
      - "3000:3000"

    command: bash

  db:
    build:
      context: .docker/db/
    container_name: e-ten-db
    volumes:
      - db-data:/var/lib/mysql
      - type: bind
        source: ".docker/db/init.sql"
        target: "/docker-entrypoint-initdb.d/init.sql"
      - type: bind
        source: ".docker/db/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-e-ten}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      TZ: "Asia/Tokyo"

volumes:
  db-data:
    driver: local
